spring.application.name=muinda-kubika


spring.datasource.url=jdbc:postgresql://localhost:5432/muinda_kubika
spring.datasource.username=postgres
spring.datasource.password=novasenha

#spring.datasource.url=${JDBC_DATABASE_URL}
#spring.datasource.username=${JDBC_DATABASE_USERNAME}
#spring.datasource.password=${JDBC_DATABASE_PASSWORD}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

# Porta do servidor
server.port=${PORT:8080}
server.address=0.0.0.0

#migrations
spring.flyway.baselineOnMigrate=true
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=validate

SPRING_FLYWAY_REPAIR_ON_MIGRATE = true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


cloudinary.cloud_name=dpsns8y1o
cloudinary.api_key=659215259758279
cloudinary.api_secret=vwNSNZIbXDoefmOYRZTcZASMhmg



spring.rabbitmq.host=leopard.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=wvfirmqp
spring.rabbitmq.password=N2tMJ1PosU6GEO0fPLTLk8YkOlmzY_nU
spring.rabbitmq.virtual-host=wvfirmqp
spring.rabbitmq.ssl.enabled=true
 ia.worker.token=change-me
ia.consumer.enabled=false
